# SIMMONS API CLIENT STUBS FOR PYTHON
# This code was auto-generated by stubgen.py
# DO NOT EDIT IT BY HAND. Edit apis.yaml instead.
# This will ensure that changes are reflected in other
# languages stubs.

import urllib2
import json

def RPC_call( path ):
	response = urllib2.urlopen( '{{server_path}}' + path )
	return json.load(response)
