# SIMMONS API CLIENT STUBS FOR PYTHON
# This code was auto-generated by stubgen.py
# DO NOT EDIT IT BY HAND. Edit apis.yaml instead.
# This will ensure that changes are reflected in other
# languages stubs.

from __common import *

###
# Beginning stubs for {{api['name']}}:
# {{api['desc']}}
###
{% for method in api['fxns'] %}
# {{method['desc']}}
def {{method['name']}}( {% for arg in method['args'] %}{{arg}}{% if not loop.last %}, {% endif %}{% endfor %} ):
	return RPC_call( {{ f( api['path'] + method['path'] ) }} )
{% endfor %}
###
# End of stubs for {{api['name']}}
###
