# SIMMONS API CLIENT STUBS FOR PYTHON
# This code was auto-generated by stubgen.py
# DO NOT EDIT IT BY HAND. Edit apis.yaml instead.
# This will ensure that changes are reflected in other
# languages stubs.

def RPC_call( path ):
	print 'tried to call to http://localhost:5000/' + path
	return None


# Beginning stubs for rooms:
# Provides data about the physical characteristics of Simmons rooms.

# Returns a list of all rooms.
def get_all(  ):
	return RPC_call( "rooms/" )

# Returns all data for a specific room.
def get_room( roomnum ):
	return RPC_call( "rooms/"+roomnum+"/" )

# End of stubs for rooms

# Beginning stubs for people:
# Provides identity-related data about the residents of Simmons residents.

# Returns a list of all current residents' usernames
def get_all(  ):
	return RPC_call( "people/" )

# Returns all data on a specific resident.
def get_person( username ):
	return RPC_call( "people/"+username+"/" )

# Returns the usernames matching the passed query. To match a query, a user has to have each space seperated token (querylet) as part of its special fields. The special fields are 'kerberos', 'firstname', and 'lastname'. Matches are case insenstive.
def query( query ):
	return RPC_call( "people/?q="+query+"" )

# End of stubs for people
