// SIMMONS API CLIENT STUBS FOR JAVASCRIPT
// This code was auto-generated by stubgen.py
// DO NOT EDIT IT BY HAND. Edit apis.yaml instead.
// This will ensure that changes are reflected in other
// languages stubs.

this.RPC_call = function( path ) {
	//print 'tried to call to http://localhost:5000/' + path;
	return "";
}


// Beginning stubs for rooms:
// Provides data about the physical characteristics of Simmons rooms.
this.rooms = {
	
	// Returns a list of all rooms.
	get_all: function(  ) {
		return RPC_call( "rooms/" );
	}

	// Returns all data for a specific room.
	get_room: function( roomnum ) {
		return RPC_call( "rooms/"+roomnum+"/" );
	}
}; // End of stubs for rooms

// Beginning stubs for people:
// Provides identity-related data about the residents of Simmons residents.
this.people = {
	
	// Returns a list of all current residents' usernames
	get_all: function(  ) {
		return RPC_call( "people/" );
	}

	// Returns all data on a specific resident.
	get_person: function( username ) {
		return RPC_call( "people/"+username+"/" );
	}

	// Returns the usernames matching the passed query. To match a query, a user has to have each space seperated token (querylet) as part of its special fields. The special fields are 'kerberos', 'firstname', and 'lastname'. Matches are case insenstive.
	query: function( query ) {
		return RPC_call( "people/?q="+query+"" );
	}
}; // End of stubs for people
