# SIMMONS API CLIENT STUBS FOR PYTHON
# This code was auto-generated by stubgen.py
# DO NOT EDIT IT BY HAND. Edit apis.yaml instead.
# This will ensure that changes are reflected in other
# languages stubs.

from __common import *

###
# Beginning stubs for login:
# Aux. methods for supporting the Simmons SSO System.
###

# Checks if the user is logged in. If so, will provide their username.
def check(  ):
	return RPC_call( "login/check" )

###
# End of stubs for login
###