# SIMMONS API CLIENT STUBS FOR PYTHON
# This code was auto-generated by stubgen.py
# DO NOT EDIT IT BY HAND. Edit apis.yaml instead.
# This will ensure that changes are reflected in other
# languages stubs.

from __common import *

###
# Beginning stubs for packages:
# Provides information about who has packages.
###

# Returns a dump object with attrs that are usernames, and values that are numbers of packages.
def get_raw(  ):
	return RPC_call( "packages/" )

# Get the number of packages the given user has.
def get_packages_for_user( username ):
	return RPC_call( "packages/"+username+"/" )

###
# End of stubs for packages
###