# SIMMONS API CLIENT STUBS FOR PYTHON
# This code was auto-generated by stubgen.py
# DO NOT EDIT IT BY HAND. Edit apis.yaml instead.
# This will ensure that changes are reflected in other
# languages stubs.

from __common import *

###
# Beginning stubs for people:
# Provides identity-related data about the residents of Simmons residents.
###

# Returns a list of all current residents' usernames
def get_all(  ):
	return RPC_call( "people/" )

# Returns all data on a specific resident.
def get_person( username ):
	return RPC_call( "people/"+username+"/" )

# Returns the usernames matching the passed query. To match a query, a user has to have each space seperated token (querylet) as part of its special fields. The special fields are 'kerberos', 'firstname', and 'lastname'. Matches are case insenstive.
def query( query ):
	return RPC_call( "people/?q="+query+"" )

###
# End of stubs for people
###