# SIMMONS API CLIENT STUBS FOR PYTHON
# This code was auto-generated by stubgen.py
# DO NOT EDIT IT BY HAND. Edit apis.yaml instead.
# This will ensure that changes are reflected in other
# languages stubs.

from __common import *

###
# Beginning stubs for profiles:
# Provides more personal information about the residents of Simmons.
###

# Returns a resident profile.
def get_profile( username ):
	return RPC_call( "profile/"+username+"/" )

###
# End of stubs for profiles
###